// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPyCz6zSe5IywOwj-fbCP1WI_OzN-PRo',
    appId: '1:608340871829:web:4bcdcd09b1decc3d02a99c',
    messagingSenderId: '608340871829',
    projectId: 'lc-price-check',
    authDomain: 'lc-price-check.firebaseapp.com',
    storageBucket: 'lc-price-check.firebasestorage.app',
    measurementId: 'G-53EH6SPS7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApE9zCusB48pj7VN8Fzfnxi1F8nq_EKCQ',
    appId: '1:608340871829:android:01980a3a11e6935502a99c',
    messagingSenderId: '608340871829',
    projectId: 'lc-price-check',
    storageBucket: 'lc-price-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRuwpCvWy7AYa3Fn2rXzL2P5buXkXk5OA',
    appId: '1:608340871829:ios:be2a0749408c709602a99c',
    messagingSenderId: '608340871829',
    projectId: 'lc-price-check',
    storageBucket: 'lc-price-check.firebasestorage.app',
    iosBundleId: 'com.example.echoappproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRuwpCvWy7AYa3Fn2rXzL2P5buXkXk5OA',
    appId: '1:608340871829:ios:be2a0749408c709602a99c',
    messagingSenderId: '608340871829',
    projectId: 'lc-price-check',
    storageBucket: 'lc-price-check.firebasestorage.app',
    iosBundleId: 'com.example.echoappproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPyCz6zSe5IywOwj-fbCP1WI_OzN-PRo',
    appId: '1:608340871829:web:11220a5613e6b5c302a99c',
    messagingSenderId: '608340871829',
    projectId: 'lc-price-check',
    authDomain: 'lc-price-check.firebaseapp.com',
    storageBucket: 'lc-price-check.firebasestorage.app',
    measurementId: 'G-5TKPNJF7N4',
  );
}
